# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [5]:
my_list
type(my_list)

list

In [4]:
import numpy as np
np.array(my_list)
print(type(np.array(my_list)))

<class 'numpy.ndarray'>


## 2d array or matrix

In [7]:
My_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(My_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.17064547, 0.90692702, 0.17212291, 0.30036708, 0.81927521])

In [20]:
np.randint(5,5)

AttributeError: module 'numpy' has no attribute 'randint'

In [17]:
np.random.randn(2)

array([1.50238685, 1.33749372])

In [28]:
np.random.randint(1,100,10)

array([71, 86, 95, 29,  8, 83, 49, 54, 52, 95])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranarr = np.random.randint(0,50,10)

In [52]:
ranarr

array([19, 30, 19, 20, 38, 36, 33, 16, 18,  7])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr.max()

38

In [54]:
ranarr.min()

7

In [55]:
ranarr

array([19, 30, 19, 20, 38, 36, 33, 16, 18,  7])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.dtype

dtype('int32')

In [43]:
from numpy.random import randint 

In [44]:
randint(2,10)

6

## Numpy Indexing and selection

In [56]:
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[8]

8

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [61]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[0:5] = 100

In [65]:
arr 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
arr = np.arange(0,11)

In [68]:
slice_of_arr = arr[0:6]

In [69]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## double bracket format to fetch info

In [71]:
arr_2d[0][0]

5

In [73]:
arr_2d[1][1]

25

## comma format to fetch info

In [74]:
arr_2d[2,1]

40

## submatrices

In [75]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

## conditional selection

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
bool_Arr = arr > 5

In [82]:
bool_Arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [83]:
arr[bool_Arr]

array([ 6,  7,  8,  9, 10])

In [84]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([0, 1, 2])

In [86]:
arr_2d = np.arange(50).reshape(5,10)

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])